apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "trial-task.fullname" . }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ include "trial-task.chart" . }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  template:
    metadata:
      name: {{ include "trial-task.fullname" . }}
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: {{ include "trial-task.chart" . }}
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-job
        image: "alpine/curl"
        command: ["curl","{{ default "https://www.freshcells.de/some/api" .Values.ApiToNotify }}"]